[server]
host = "127.0.0.1"
port = 8080
workers = 4

[database]
url = "postgres://postgres:postgres@localhost/uhi_db"
max_connections = 5
min_connections = 1

[logging]
level = "debug"
format = "pretty" 