[server]
host = "127.0.0.1"
port = 8081
workers = 2

[database]
url = "postgres://postgres:postgres@localhost/uhi_dev_db"
max_connections = 5
min_connections = 1

[logging]
level = "debug"
format = "pretty" 